.TH "mgs::FieldParms< T, Interant >" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::FieldParms< T, Interant >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compute\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldParms\fP (T gc, T dt, Interant il, T er)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBgravitational_constant\fP"
.br
.ti -1c
.RI "T \fBdelta_t\fP"
.br
.ti -1c
.RI "Interant \fBiter_limit\fP"
.br
.ti -1c
.RI "T \fBescape_radius\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Interant>
.br
struct mgs::FieldParms< T, Interant >"
\fBField\fP Parameters for MGS\&. These determine the nature of the MGS fractal that is generated\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
