.TH "mgs::PosVel" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::PosVel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compute\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPosition\fP \fBp\fP"
.br
.ti -1c
.RI "\fBVelocity\fP \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
For some operations, it helps to have Position and Velocity combined\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
