.TH "mgs::FieldParmsSimulation< T, I >" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::FieldParmsSimulation< T, I >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBmgs::FieldParms< T, I >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldParmsSimulation\fP (T grav_const=0\&.01, T dt=0\&.1, I iter=100, T escape_r=200, T sim_speed=1\&.0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBsimulation_speed\fP"
.br
.ti -1c
.RI "T \fBgravitational_constant\fP"
.br
.ti -1c
.RI "T \fBdelta_t\fP"
.br
.ti -1c
.RI "I \fBiter_limit\fP"
.br
.ti -1c
.RI "T \fBescape_radius\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
