.TH "mgs::Bounds" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::Bounds
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compute\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCoordinate\fP \fBnm\fP"
.br
.ti -1c
.RI "\fBCoordinate\fP \fBpm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A bounding box for the field 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
