.TH "mgs::march::MakeMesh" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::march::MakeMesh
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marching_tetrahedra\&.h>\fP
.PP
Inherits \fBmgs::march::Pipeline\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMakeMesh\fP (const \fBMakeTesselation\fP &tess)"
.br
.in -1c
.SH "Detailed Description"
.PP 
We take the results from \fBMakeTesselation\fP to now make the mesh\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
