.TH "mgs::march::Pipeline" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::march::Pipeline
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marching_tetrahedra\&.h>\fP
.PP
Inherited by \fBmgs::march::MakeMesh\fP, and \fBmgs::march::MakeTesselation\fP\&.
.SH "Detailed Description"
.PP 
Production is done in a pipeline fashion, and later will be made lazy\&. All classes involved in the pipeline shall be derived from this one\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
