.TH "mgs::Star" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::Star
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStar\fP (floating_t m, \fBPosition\fP pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "floating_t \fBmass\fP"
.br
.ti -1c
.RI "\fBPosition\fP \fBposition\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
