.TH "mgs::SCB" 3 "Sat Apr 13 2019" "Version 1" "Mitchell Gravity Set, 4th Generation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mgs::SCB
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBicon_file\fP"
.br
.ti -1c
.RI "SlotGUI \fBgslot\fP"
.br
.ti -1c
.RI "SlotCF \fBcslot\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Mitchell Gravity Set, 4th Generation from the source code\&.
